language: php

php:
  - 5.5
  - 5.6
  - 7

matrix:
  include:
    - php: 5.6
      env: SYMFONY_VERSION='2.3.*'
    - php: 5.6
      env: SYMFONY_VERSION='2.5.*'
    - php: 5.6
      env: SYMFONY_VERSION='2.7.*'
    - php: 5.6
      env: SYMFONY_VERSION='2.8.*'
    - php: 5.6
      env: SYMFONY_VERSION='3.0.*'
    - php: 5.6
      env: SYMFONY_VERSION='dev-master'
    - php: 7
      env: SYMFONY_VERSION='dev-master'
  allow_failures:
    - env: SYMFONY_VERSION='dev-master'


before_script:
    - sh -c 'if [ "$SYMFONY_VERSION" != "" ]; then composer require --dev --no-update symfony/symfony=$SYMFONY_VERSION; fi;'
    - composer install --dev --prefer-source

script:
    - phpunit --coverage-text


